/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import conect.conexao;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
/**
 *
 * @author santiago
 */
public class Agenda extends javax.swing.JFrame {

    conexao con_agenda;
    int navega=0;
    
    
    public Agenda() {
        
        
        initComponents();
        
        con_agenda = new conexao();
        con_agenda.conecta();
        
        con_agenda.executeSQL("select * from Contatos");
        try{
            con_agenda.resultset.first();
            tf_Codigo.setText(con_agenda.resultset.getString("codigo"));
            tf_Nome.setText(con_agenda.resultset.getString("nome"));
            tf_Email.setText(con_agenda.resultset.getString("email"));
            tf_Telefone.setText(con_agenda.resultset.getString("telefone"));
            tf_Foto.setText(con_agenda.resultset.getString("foto"));
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não Localizou Dados: \n"
                    + erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        painelPrincipal = new javax.swing.JPanel();
        lb_Nome = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        lb_Telefone = new javax.swing.JLabel();
        lb_Foto = new javax.swing.JLabel();
        lb_Ft = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_Primeiro = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        btn_Ultimo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Deletar = new javax.swing.JButton();
        lb_Posicao = new javax.swing.JLabel();
        tf_Codigo = new javax.swing.JTextField();
        tf_Foto = new javax.swing.JTextField();
        tf_Nome = new javax.swing.JTextField();
        tf_Email = new javax.swing.JTextField();
        tf_Telefone = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        painelSobre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contatos");
        setForeground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda de Contatos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        painelPrincipal.setForeground(new java.awt.Color(240, 240, 240));
        painelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lb_Nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Nome.setText("Nome.:");

        lb_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Email.setText("Email.:");

        lb_Telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Telefone.setText("Telefone.:");

        lb_Foto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Foto.setText("Foto");

        lb_Ft.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Ft.setText("Foto");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_Primeiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Primeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/primeiro.png"))); // NOI18N
        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Anterior.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/anterior.png"))); // NOI18N
        btn_Anterior.setText("Anterior");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Proximo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proximo.png"))); // NOI18N
        btn_Proximo.setText("Próximo");
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        btn_Ultimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ultimo.png"))); // NOI18N
        btn_Ultimo.setText("Último");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salva.png"))); // NOI18N
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Deletar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/deleta.png"))); // NOI18N
        btn_Deletar.setText("Deletar");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        lb_Posicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_Posicao.setText("Posição");

        tf_Codigo.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Codigo.setText("0");

        tf_Foto.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        tf_Nome.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NomeActionPerformed(evt);
            }
        });

        tf_Email.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        tf_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EmailActionPerformed(evt);
            }
        });

        tf_Telefone.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        btnNew.setBackground(new java.awt.Color(153, 255, 51));
        btnNew.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        btnNew.setText("Novo Registro");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(btn_Primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Proximo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Ultimo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Deletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addGap(28, 28, 28)
                        .addComponent(lb_Posicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(lb_Telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(lb_Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(lb_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_Ft, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(lb_Foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Nome)
                            .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Email)
                            .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Telefone)
                            .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_Ft, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Foto)
                    .addComponent(tf_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Anterior)
                        .addComponent(btn_Primeiro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Ultimo)
                        .addComponent(btn_Proximo)))
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Deletar)
                    .addComponent(lb_Posicao)
                    .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Agenda", painelPrincipal);

        painelSobre.setBackground(new java.awt.Color(255, 255, 255));
        painelSobre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("<html>\nEste é apenas um trabalho realizado<br> para práticar conceitos aprendidos  durante o curso.\nUm simples CRUD  Básico sobre uma agenda na qual  você poderá guardar seus melhores  contatos.\n</html>");

        javax.swing.GroupLayout painelSobreLayout = new javax.swing.GroupLayout(painelSobre);
        painelSobre.setLayout(painelSobreLayout);
        painelSobreLayout.setHorizontalGroup(
            painelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSobreLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        painelSobreLayout.setVerticalGroup(
            painelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSobreLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Sobre", painelSobre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
        // TODO add your handling code here:
        try{
            con_agenda.resultset.last();
            mostrar_Dados();
          
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel ir para"+
                    "o Ultimo Registro \n "+erro);
        }
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
        try{
            String cod = tf_Codigo.getText();
            String nome = tf_Nome.getText();
            String email = tf_Email.getText();
            String telefone = tf_Telefone.getText();
            String foto = tf_Foto.getText();
            if (foto.isEmpty()) {
                foto = "default.jpg";
            }
            if (cod.isEmpty()) {
                //Inserção no Banco de Dados
                String insertSQL = "Insert into Contatos (nome, email, telefone,"+
                "foto) values ('"+nome+"','"+email+"',"+
                "'"+telefone+"','"+foto+"')";
                con_agenda.statement.executeUpdate(insertSQL);
            } else {
                // Atualização do Banco 
                String updateSQL = "Update Contatos set "
                        + "nome = '"+nome+"',"
                        + "email = '"+email+"',"
                        + "telefone = '"+telefone+"',"
                        + "foto = '"+foto+"' where codigo = '"+cod+"' ";
                System.out.println(updateSQL);
                con_agenda.statement.execute(updateSQL);
            }
            JOptionPane.showMessageDialog(null, "Salvo Com Sucesso!!!");
            con_agenda.executeSQL("select * from Contatos order by codigo asc");
            con_agenda.resultset.first();
            mostrar_Dados();

        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro ao Gravar");

        }
        
        
        
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed
        // TODO add your handling code here:
         try{
            con_agenda.resultset.first();
            mostrar_Dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi Possivel ir para"+
                    "o primerio registro\n"+erro);
        }
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
        // TODO add your handling code here:
        try{
            
            con_agenda.resultset.previous();
            mostrar_Dados();
            navega = 1;
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel ir para"+
                    "o Registro Anterior \n"+erro);
        }
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
        // TODO add your handling code here:
          try{
            con_agenda.resultset.next();
            mostrar_Dados();
            navega=2;
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel ir para"+
                    "o registro seguinte \n "+erro);
        }
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="select * from Contatos where codigo = "+tf_Codigo.getText();
            con_agenda.executeSQL(sql);
            con_agenda.resultset.first();
            String nome ="Deletar o Contato : "+con_agenda.resultset.getString("nome");
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome,"Remover"+
                    "Contatos", JOptionPane.YES_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION){
                
                sql = "delete  from Contatos where codigo = "+tf_Codigo.getText();
                
                int conseguiu_excluir = con_agenda.statement.executeUpdate(sql);
                
                if(conseguiu_excluir ==1){
                    JOptionPane.showMessageDialog(null,"Excluido com Sucesso!!!");
                    //atualiza o resultset
                    con_agenda.executeSQL("select * from Contatos");
                    
                    //posiciona no primeiro registro
                    con_agenda.resultset.first();
                    mostrar_Dados();
                }
            } else 
                return ;
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Erro ao Excluir!\n"+ erro);
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        JFileChooser busca_foto = new JFileChooser();
        busca_foto.setCurrentDirectory(new File("C:/Users/santiago/"+
                "Documentos/NetBeansProjects/AgendaContatos/src/imagens"));
        busca_foto.setDialogTitle("Carregar imagem do funcionario");
        busca_foto.showOpenDialog(this);
        String foto = busca_foto.getSelectedFile().getName();
        tf_Foto.setText(foto);
        lb_Ft.setText("");
        lb_Ft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+tf_Foto.getText())));
        
        busca_foto.setDialogTitle("Carregar imagem do funcionario");
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Não Foi Possivel Carregar a Foto");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        tf_Nome.setText("");
        tf_Email.setText("");
        tf_Telefone.setText("");
        tf_Foto.setText("default.jpg");
        tf_Codigo.setText("");
        lb_Ft.setText("");
        lb_Ft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+tf_Foto.getText())));
        
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void tf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Deletar;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_Ultimo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_Foto;
    private javax.swing.JLabel lb_Ft;
    private javax.swing.JLabel lb_Nome;
    private javax.swing.JLabel lb_Posicao;
    private javax.swing.JLabel lb_Telefone;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSobre;
    private javax.swing.JTextField tf_Codigo;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JTextField tf_Foto;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Telefone;
    // End of variables declaration//GEN-END:variables
public void mostrar_Dados(){
    try{
        tf_Nome.setText(con_agenda.resultset.getString("nome"));
        tf_Email.setText(con_agenda.resultset.getString("email"));
        tf_Telefone.setText(con_agenda.resultset.getString("telefone"));
        tf_Foto.setText(con_agenda.resultset.getString("foto"));
        tf_Codigo.setText(con_agenda.resultset.getString("codigo"));
        lb_Ft.setText("");
        lb_Ft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+tf_Foto.getText())));
        
    }
    catch(SQLException erro){
        if (navega == 1){
            JOptionPane.showMessageDialog(null, "Já esta no primeiro Registro");
        }else if (navega ==2){
            JOptionPane.showMessageDialog(null, "Já está no ultimo registro");
        }else 
            JOptionPane.showMessageDialog(null,"Não Localizou Dados:\n"+ erro);
       navega = 0;
    }
}
}